Attempt to fix the problem which causes cpuinfo.c to fail compilation on MacIntel system (OSX/gcc4 on Intel):
utils/cpuinfo.c:44: error: PIC register '%ebx' clobbered in 'asm'